### ISSUE TITLE
v3.0 二維碼展示頁面月份無法顯示二位數月份

### ISSUE THREAD

**Issue by EricCat** [sunhouyun/HealthyCode#4]
您好，進入10月份後，二維碼展示頁面的月份數字就無法顯示了。
如下圖所示：
![Screenshot_20211006-012227__01__01](https://user-images.githubusercontent.com/4900138/136494387-0b74dfe2-467c-488f-b8ca-46582d6e35b6.jpg)

**Comment by sunhouyun** [comment]
立刻修复.


---原始邮件---
发件人: &quot;Wes ***@***.***&gt;
发送时间: 2021年10月8日(周五) 中午11:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [sunhouyun/HealthyCode] v3.0 二維碼展示頁面月份無法顯示二位數月份 (#4)




 
您好，進入10月份後，二維碼展示頁面的月份數字就無法顯示了。
 如下圖所示：
 
 
&mdash;

**Comment by EricCat** [comment]
这个问题在11月份已经自动修复了。现关闭这个issue了。
